org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod Properties
mod_id=immersivefluids
mod_name=Immersive-Fluids
mod_license=MIT
mod_version=0.1.3.0-1.21.1
mod_group_id=github.jodevnull
mod_description=Physics based behaviour for your minecraft fluids.
mod_authors=SirWashington, Ewoudje, Ruby, CoolMineman, jo-devnull

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# NeoForge
neo_version=21.1.227
neo_version_range=[21,)
loader_version_range=[4,)
